enable-magisk-update = false # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[AdobeLightroom]
enabled = false
version = "8.2.3"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/lightroom/"
uptodown-dlurl = "https://adobe-lightroom-mobile.en.uptodown.com/android"

[AmazonShopping]
enabled = false
version = "28.18.0.100"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-shopping/"
uptodown-dlurl = "https://amazon-shopping.en.uptodown.com/android"

[Backdrops]
enabled = false
apkmirror-dpi = "120-640dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/backdrops/backdrops-wallpapers/"
# uptodown-dlurl = "https://backdrops.en.uptodown.com/android"

[Bandcamp]
enabled = false
# apkmirror-dlurl = "https://www.apkmirror.com/apk/bandcamp-inc/bandcamp/"
uptodown-dlurl = "https://bandcamp.en.uptodown.com/android"

[Duolingo]
enabled = false
apkmirror-dpi = "120-640dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/duolingo/duolingo-duolingo/"
# uptodown-dlurl = "https://duolingo.en.uptodown.com/android"
included-patches = "'Disable ads'"
exclusive-patches = true

[Facebook]
enabled = false
# arch = "arm-v7a"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/facebook/"
uptodown-dlurl = "https://facebook.en.uptodown.com/android"

[GoogleNews]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/google-news/"
# uptodown-dlurl = "https://google-play-newsstand.en.uptodown.com/android"

[GooglePhotos]
enabled = true
# arch = "arm-v7a"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"

[IconPackStudio]
enabled = true
# apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/icon-pack-studio/"
uptodown-dlurl = "https://icon-pack-studio.en.uptodown.com/android"

[Instagram]
enabled = false
arch = "arm-v7a"
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
# uptodown-dlurl = "https://instagram.en.uptodown.com/android"

[MemeGenerator]
enabled = true
apkmirror-dpi = "120-640dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/zombodroid/meme-generator-free/"
# uptodown-dlurl = "https://meme-generator-free.en.uptodown.com/android"

[Messenger]
enabled = true
# arch = "arm-v7a"
# apkmirror-dpi = "360-480dpi"
# apkmirror-dlurl = "https://apkmirror.com/apk/facebook-2/messenger/"
uptodown-dlurl = "https://facebook-messenger.en.uptodown.com/android"

[MiFitness]
enabled = false
arch = "arm-v7a"
version = "1.1.44"
apkmirror-dlurl = "https://www.apkmirror.com/apk/beijing-xiaomi-mobile-software-co-ltd/mi-wear-%e5%b0%8f%e7%b1%b3%e7%a9%bf%e6%88%b4/"

[NetGuard]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/marcel-bokhorst/netguard-no-root-firewall/"

[Photomath]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photomath/"

[Pixiv]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/pixiv-inc/pixiv/"

[RAR]
enabled = false
arch = "arm-v7a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/rarlab-published-by-win-rar-gmbh/rar/"

[Reddit]
enabled = false
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"

[SolidExplorer]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/neatbytes/solid-explorer-beta/"

[SoundCloud]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/soundcloud/soundcloud-soundcloud/"

[SoundConnect]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/sony-corporation/sony-headphones-connect/"

[Spotify]
enabled = false
uptodown-dlurl = "https://spotify.en.uptodown.com/android"

[SpotifyLite]
enabled = false
version = "1.9.0.56456"
uptodown-dlurl = "https://spotify-lite.en.uptodown.com/android"

[Stocard]
enabled = false
apkmirror-dpi = "120-640dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/stocard-gmbh/stocard-rewards-cards-wallet/"

[SyncForLemmy]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/sync-apps-ltd/sync-for-lemmy/"

[TickTick]
enabled = false
apkmirror-dpi = "120-640dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/ticktick-limited/ticktick-to-do-list-with-reminder-day-planner/"

[TikTok]
enabled = false
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"

[Trakt]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/trakt/trakt/"

[Tumblr]
enabled = false
apkmirror-dpi = "120-640dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tumblr-inc/tumblr/"

[Twitch]
enabled = false
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch/"

[Twitter]
enabled = false
apkmirror-dpi = "120-640dpi"
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"

[WindyApp]
enabled = false
apkmirror-dpi = "120-640dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/windy-weather-world-inc/windy-wind-weather-forecast/"

[YTMusic]
enabled = false
arch = "arm-v7a"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"

[YouTube]
enabled = false
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"

[Yuka]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/yuka-apps/yuka-food-cosmetic-scan/"
